### PR TITLE
Microsoft di and roslyn compiler

### PR DESCRIPTION
**Pull request by bounav**
Using the Microsoft.Extensions.DependencyInjection apis to resolve dependencies

- Removed `ISparkServiceInitialize` and `ISparkServiceContainer` (and it's implementation)
- Constructor injection is used instead of auto-initializing properties
- New `IBatchCompiler` interface so that we can use different compilers
    - ~2x performance improvement when compiling views with Roslyn
    - CodeDom compilation can still be used at the moment (class marked as obsolete)
    - CodeDom marked as obsolete (as it will not generating code for .net core) and wrapped into `#if NETFRAMEWORK` block
- Fixed a bug preventing the pre-compilation of templates for a generic controller
- New implementation of `ICacheService` that is works on _.net standard_ (InMemoryCache)

### CODE REVIEW

**Comment by bounav** [comment]
I found a problem when using roslyn to compile the views: each time a view is compile an assembly is loaded into memory and never released. This means spark will eat up all the memory available and eventually `OutOfMemoryException` are thrown.

**Comment by RobertTheGrey** [comment]
Good catch! I'll take a look again when you've found a workaround for this.

**Comment by bounav** [comment]
I can't think of a fix for .net framework. I think the best it to carry on using the non roslyn compiler.

For .net core loading the assemblies into a MetadataLoadContext might be an avenue to explore.

**Comment by RobertTheGrey** [comment]
Is it worth going down the Source Generation route during compile time maybe?

**Comment by bounav** [comment]
> Is it worth going down the Source Generation route during compile time maybe?

Definitely something worth exploring. It would be ideal to have the same options/behaviour as with MVC Razor (e.g. the choice to compile the views are build time (default) or to leave it for later at runtime).

I couldn't find any docs explaining how Microsoft does compile their razor views at build time...

**Pull request merged**
